language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.6.*

services:
  - memcached

before_script:
  - phpenv config-add .travis-config.ini
  - composer self-update
  - composer install

script:
  - phpunit
